#!/bin/bash


input_folder="./GWAS/"
input_files=(${input_folder}*.txt)


for input_file in "${input_files[@]}"; do
   
    filename=$(basename -- "${input_file}")
    filename_no_ext="${filename%.*}"

   
    output_file="./Lung/${filename_no_ext}"

    
    ./smr-1.3.1 --bfile ./g1000_eur/g1000_eur --gwas-summary "${input_file}" --beqtl-summary ./Lung_eQTL/Lung.lite --out "${output_file}"_Lung --thread-num 10
done
